// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  firebaseConfig: {
    apiKey: 'AIzaSyBpUItBBPU09oZxWowH3-fD2uyrzYwx5qE',
    authDomain: 'dice-poker-api.firebaseapp.com',
    databaseURL: 'https://dice-poker-api.firebaseio.com',
    projectId: 'dice-poker-api',
    storageBucket: 'dice-poker-api.appspot.com',
    messagingSenderId: '546832395191',
    appId: '1:546832395191:web:d8a562cdb018906db05632',
    measurementId: 'G-3PCWF8B50T',
  },
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
